workflow:
  rules:
    - if: '($CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == "main") && $CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
  - trigger

backend-trigger:
  stage: trigger
  trigger:
    include: backend/.gitlab-ci.yml

frontend-trigger:
  stage: trigger
  trigger:
    include: frontend/.gitlab-ci.yml
