workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")

stages:
  - trigger

backend-trigger:
  stage: trigger
  trigger:
    include: backend/.gitlab-ci.yml

frontend-trigger:
  stage: trigger
  trigger:
    include: frontend/.gitlab-ci.yml
