spring:
  application:
    name: ServiceHub

  # [TODO]: Need to update configuration later on
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/service_hub
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver